include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/features/map/contracts/**

linter:
  rules:
    avoid_print: true
    directives_ordering: true
    unawaited_futures: true
